# Generated by Django 4.2.3 on 2023-07-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('neighborhood', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
            ],
        ),
    ]
