# Generated by Django 4.2.3 on 2023-07-03 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('Pedido Realizado', 'Pedido Realizado'), ('Em Andamento', 'Em Andamento'), ('Entregue', 'Entregue')], default='Pedido Realizado', max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='cart.cart')),
            ],
        ),
    ]
