# Generated by Django 4.2.3 on 2023-07-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('Pedido Realizado', 'Pedido Realizado'), ('Em Andamento', 'Em Andamento'), ('Entregue', 'Entregue'), ('Cancelado', 'Cancelado')], default='Pedido Realizado', max_length=50)),
                ('total_value', models.FloatField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
