# Generated by Django 4.2.3 on 2023-07-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pedido Realizado', 'Pedido Realizado'), ('Em Andamento', 'Em Andamento'), ('Entregue', 'Entregue'), ('Cancelado', 'Cancelado')], default='Pedido Realizado', max_length=50),
        ),
    ]
