# Generated by Django 4.2.3 on 2023-07-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Alimentos', 'Alimentos'), ('Higiene', 'Higiene'), ('Bebidas', 'Bebidas'), ('Produtos de Beleza', 'Produtos De Beleza'), ('Não Informado', 'Nao Informado')], default='Não Informado', max_length=50)),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stock', models.IntegerField()),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
